# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Debug
      run: dotnet build --no-restore -p:Configuration=Debug
    - name: Build Release
      run: dotnet build --no-restore -p:Configuration=Release
    - name: Pack Release
      run: dotnet pack --no-restore --no-build -p:Configuration=Release
    - name: Upload bin
      uses: actions/upload-artifact@v4
      with:
        name: bin
        path: out/bin
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: out/packages
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory out/TestResults
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: out/TestResults
