name: Upload dotnet package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build Release
        run: dotnet build --no-restore -p:Configuration=Release
      - name: Pack Release
        run: dotnet pack --no-restore --no-build -p:Configuration=Release
      - run: dotnet build --no-restore -p:Configuration=Release
      - name: Create the package
        run: dotnet pack --configuration Release
      - name: Publish the package to GPR
        run: dotnet nuget push out/packages/Release/*.nupkg --source github --skip-duplicate
