name: Upload dotnet package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          source-url: https://nuget.pkg.github.com/localtoast9001/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build Release
        run: dotnet build --no-restore -p:Configuration=Release
      - name: Pack Release
        run: dotnet pack --no-restore --no-build -p:Configuration=Release
      - run: dotnet build --no-restore -p:Configuration=Release
      - name: Create the package
        run: dotnet pack --configuration Release
      - name: Zip img2gcode
        run: zip -r out/bin/img2gcode.zip out/bin/img2gcode/Release/net8.0
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/bin/img2gcode.zip
      - name: Publish the package to GPR
        run: dotnet nuget push out/packages/Release/*.nupkg --source github --skip-duplicate
